version: '3.8'

services:
  postgres:
    image: postgres:16-alpine
    container_name: watts-postgres
    environment:
      POSTGRES_USER: watts
      POSTGRES_PASSWORD: password
      POSTGRES_DB: watts
    ports:
      - '5439:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U watts']
      interval: 10s
      timeout: 5s
      retries: 5

  dragonfly:
    image: docker.dragonflydb.io/dragonflydb/dragonfly
    container_name: watts-dragonfly
    ulimits:
      memlock: -1
    command:
      [
        '--default_lua_flags=allow-undeclared-keys',
        '--requirepass=dragonfly',
        '--proactor_threads',
        '1',
        '--maxmemory=256mb',
        '--admin_port=6380',
        '--admin_nopass',
        '--slowlog_log_slower_than=10000',
        '--slowlog_max_len=128'
      ]
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 256M
    ports:
      - '6379:6379'
      - '6380:6380'
    volumes:
      - dragonfly_data:/data

volumes:
  postgres_data:
  dragonfly_data:
